 scenarios:
  - name: 'Scenario 0'
    messages:
      - from: 1               # id of client sender
        to: 10                 # id of client receiver
        content: 'From 1!'    # content of message
      - from: 2
        to: 9
        content: 'From 2!'
  - name: 'Scenario 1'
    messages:
      - from: 1
        to: 9
        content: 'From 1!'
      - from: 2
        to: 10
        content: 'From 2!'